language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3

install:
  - pip install --use-mirrors pytest
  - pip install --use-mirrors six
  - pip install --use-mirrors tornado

script:
  - py.test
